### ISSUE TITLE
Licensing for the SMRF Eagle files?

### ISSUE THREAD

**Issue by timchurches** [4ms/SMR#1]
Hi Dan,

A question was raised on MW about the licensing of the Eagle files for your SMR filter design. All the firmware source code for it is clearly licensed under the MIT license, but the text of that license refers to software only. There doesn't seem to be any explicit licensing for the hardware design files - something like CC-BY-SA, which is what Olivier Gillet uses for his hardware design files. Just a line added to the README or LICENSE files for the repo would suffice, i think.

Regards,

Tim C

**Comment by 4ms** [comment]
Hi Tim,
Thanks for bringing that up. It was an oversight to post the hardware files without a license! My intent is to provide others the necessary files to build or modify their own SMR, and also to provide some reference material for others who are developing new projects, but I don't want anyone except 4ms to sell SMRs. I'm considering the CC BY-NC-SA license, but I need to look into this further to make sure this license doesn't prohibit such things as group buys for components (which makes sense and I want to support). Any thoughts or experience you have in this would be appreciated. Thanks, Dan

**Comment by timchurches** [comment]
Dan,

Yes, prevention of commercial exploitation is a tricky issue when it comes to open-source licensing. The received wisdom in open-source software circles is that non-commercial clauses or provisions in licenses are a hiding-to-nothing, and are either unenforceable in law (too many loop-holes), or have unintended consequences (such as prohibiting legitimate use in educational institutions that collect fees - which is most universities, colleges etc in most countries, these days).

However, I think that is a rather binary view of the way society and the law works - perhaps not an unexpected worldview amongst programmers. Even if non-commercial clauses are not enforceable in all circumstances, using a license which clearly conveys the wishes of the copyright holder that the IP not be commercially exploited is still worthwhile, in my opinion. I think this is particularly so in the modular synth DIY community, where there seems to be a strong appreciation of both IP and moral rights to module designs, and lots of opprobrium heaped on anyone who doesn't respect those rights, although there is not much understanding of open-source licensing, at least not yet.

All that by way of saying that the CC-BY-SA-NC license seems like a sound choice to me. Its copyleft intentions (in the ShareAlike clauses) are fairly clear, even if the wording is not completely water-tight. You can always provide extra advice to those who want to use the material - such as an educational institution - but who might be unsure whether the NC clauses apply to them - just ask them to contact you, and you can issue them with a non-transferrable special purpose license (IP can be distributed under more than one license, and as copyright holder, you are at liberty to grant special licenses to particular parties if you wish). By "license", just an email saying "yeah, you can use it in your educational institution even though you charge students fees, just abide by all other aspects of the CC-BY-SA-NC license please" will do.

I would also make it clear to everyone that the NC clauses are intended to prohibit both sale and barter of DIY builds of the SMRF, to avoid people making them and trading for other modules.

Olivier Gillet has now added a request on his GitHub README that DIY builds of his modules (including panels) do not use "Mutable Instruments", because it is a protected trademark, and that DIY versions of the PCBs use quite different names for the module, so that there can be no mistaking them for the genuine factory-built article. But the CC-BY-SA license man must be retained, as well as the copyright attribution to Oliver Gillet. All those seem like a sound policies which you might also want to adopt and articulate.

Regards,

Tim C

**Comment by 4ms** [comment]
Excellent, thank you for the advice. I agree it may not be convenient or realistic to defend a non-commercial clause, but I feel better making my intent clear about non-commercial use. Hopefully anyone interested in grey-area use (such as the example you give of an institution charging fees for an educational experience) would contact me to discuss.

I've updated the license file and README to reflect the CC-BY-SA-NC license for the hardware. Enjoy!

**Comment by timchurches** [comment]
Dan,

Just FYI, see https://www.muffwiggler.com/forum/viewtopic.php?p=2222032#2222032

Hmmmm....

**Comment by 4ms** [comment]
My intent is to prohibit commercial activity only in the sense written in the license, that is: "not **primarily intended for or directed towards** commercial advantage or monetary compensation". I chose this license because it allows for some money to change hands (which is inevitable when doing many types of projects), and yet it prohibits endeavors that are **primarily** intended to make money, or for commercial advantage (which I understand to mean, for example, taking an initial financial loss to drive someone else out of business).
So... looking at the numbers, I see the SMR PCB listed for 3.50GBP. A major online pcb house (PCBcart.com) quotes me at 5.04USD which is 3.48GBP at today's rates (including shipping to the USA, which I presume is similar to shipping to the UK). Prices at various board houses may vary, as well as shipping costs, etc, but in my experience they are pretty close to each other. Thus it seems that the person managing the orders and the production of the PCBs, as well as collecting the money is not making much profit, if any. It seems clear to me that the endeavor is not primarily intended for nor directed towards monetary compensation.
If I'm misunderstanding the price of the SMR PCB, then my argument is out the window. But at 3.50 GBP, I'd say this is not a violation of the license.
